# Generated by Django 4.1.2 on 2022-10-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="items.item",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="items.category",
            ),
        ),
    ]
